const FLAGS = {

    // ===== SIGLAS FIFA =====
    RSA:"za",
    CAN:"ca",
    BRA:"br",
    JPN:"jp",
    GER:"de",
    NED:"nl",
    MAR:"ma",
    CIV:"ci",
    MEX:"mx",
    USA:"us",
    ARG:"ar",
    URU:"uy",
    POR:"pt",
    ESP:"es",
    FRA:"fr",
    ENG:"gb-eng",
    BEL:"be",
    SUI:"ch",
    COL:"co",
    PAR:"py",
    AUS:"au",
    TUR:"tr",
    KOR:"kr",
    CZE:"cz",
    QAT:"qa",
    BIH:"ba",
    HAI:"ht",
    SCO:"gb-sct",
    NZL:"nz",
    EGY:"eg",
    CPV:"cv",
    KSA:"sa",
    NOR:"no",
    SEN:"sn",
    IRQ:"iq",
    AUT:"at",
    ALG:"dz",
    JOR:"jo",
    UZB:"uz",
    COD:"cd",
    ECU:"ec",
    CUR:"cw",
    SWE:"se",
    TUN:"tn",
    IRN:"ir",
    GHA:"gh",
    PAN:"pa",

    // ===== NOMES =====
    "África do Sul":"za",
    "Canadá":"ca",
    "Brasil":"br",
    "Japão":"jp",
    "Alemanha":"de",
    "Holanda":"nl",
    "Países Baixos":"nl",
    "Marrocos":"ma",
    "Costa do Marfim":"ci",
    "México":"mx",
    "EUA":"us",
    "Estados Unidos":"us",
    "Argentina":"ar",
    "Uruguai":"uy",
    "Portugal":"pt",
    "Espanha":"es",
    "França":"fr",
    "Inglaterra":"gb-eng",
    "Bélgica":"be",
    "Suíça":"ch",
    "Colômbia":"co",
    "Paraguai":"py",
    "Austrália":"au",
    "Turquia":"tr",
    "Coreia do Sul":"kr",
    "República Tcheca":"cz",
    "Catar":"qa",
    "Bósnia":"ba",
    "Bósnia e Herzegovina":"ba",
    "Haiti":"ht",
    "Escócia":"gb-sct",
    "Nova Zelândia":"nz",
    "Egito":"eg",
    "Cabo Verde":"cv",
    "Arábia Saudita":"sa",
    "Noruega":"no",
    "Senegal":"sn",
    "Iraque":"iq",
    "Áustria":"at",
    "Argélia":"dz",
    "Jordânia":"jo",
    "Uzbequistão":"uz",
    "RD Congo":"cd",
    "República Democrática do Congo":"cd",
    "Equador":"ec",
    "Curaçao":"cw",
    "Suécia":"se",
    "Tunísia":"tn",
    "Irã":"ir",
    "Gana":"gh",
    "Panamá":"pa"

};

window.FLAGS = FLAGS;
